### PR TITLE
Update node interface to allow keto-tokens to use appropriate aws tags

### PR DESCRIPTION
**Pull request by lewismarshall**
Need this in first for running keto-tokens from keto-k8 (it consumes the value and passes to keto-tokens).

### CODE REVIEW

**Comment by vaijab** [comment]
Why do we need another method if we already pass this in via userdata https://github.com/UKHomeOffice/keto/blob/master/pkg/userdata/userdata.go#L36?

**Comment by lewismarshall** [comment]
It's just a simpler single place to manage rather than shuffling the value through command line params into keto-k8 and on into keto-tokens. Happy to remove it if you think it's fundamentally wrong...

I'll add the PR that uses it in keto-k8 if you want..

**Comment by vaijab** [comment]
No, it's cool, I am just worried that we'll end up exposing every property as a method. Will refactor probably into something else in the future.

**Comment by lewismarshall** [comment]
@vaijab - review pls ;)

**Pull request merged**
