### PR TITLE
publish a github release on push to master

### PR DESCRIPTION
**Pull request by Joseph-Irving**
This should be only be merged in once https://github.com/UKHomeOffice/keto/pull/85 is done as otherwise it tries to publish everything three times which causes some weirdness

### CODE REVIEW

**Comment by lewismarshall** [comment]
@Joseph-Irving a little rebase required...

**Comment by Joseph-Irving** [comment]
Indeed, it was kash's fault

**Comment by Joseph-Irving** [comment]
I have rebased

**Comment by vaijab** [comment]
LGTM

**Pull request merged**
